baseURL:  https://mrphys.github.io/homepage/ #http://localhost:1313/test #
title: "Translational Cardiac MRI Group"
# relativeURLs: true

menu:
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 20
    - identifier: people
      name: People
      url: /people/
      weight: 30

params:
  description: Developing and validating novel methods of imaging the cardiovascular system
  img_home: img/home/banner.jpg
  img_404: img/404.jpg
  sponsors: [img/sponsors/ucl.png, img/sponsors/bhf.png, img/sponsors/gosh.png, img/sponsors/royalfree.png]
  email: rmhitly@ucl.ac.uk
  social:
    github: "mrphys"
